### ISSUE TITLE
bug when using ./evm2near (.sol to .wasm)

### ISSUE THREAD

**Issue by Scofield-04-21-076** [aurora-is-near/evm2near#3]
Using command **./evm2near my_contract.sol -o my_contract.wasm -b near**, I get the following error: **Failed to compile Solidity ABI: unexpected output from `solc'**

I was able to figure out that this error occurs if the contract uses a constructor, example:
```Solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.16;

contract Calc {

    address public owner;
    uint256 public num;

    constructor() {
        owner = msg.sender;
        num = 0;
    }

    function multiply(int a, int b) public pure returns (int) {
        return a * b;
    }
}
```

This error also occurs if events are used in the contract, example: 
```Solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.16;

contract Calc {

    address public owner;
    uint256 public num;

    event Multiply(uint256 mul);

    function multiply(uint256 a, uint256 b) public returns (uint256) {

        uint256 c = a * b;

        emit Multiply(c);

        return c;
    }
}
```

**Comment by birchmd** [comment]
Thanks for the report @Scofield-04-21-076 . This project is still in very early stages, so we do not yet support everything in Solidity (evidently).

It's an interesting design question how these features should be added to `evm2near`.

In the case of the constructor, there is an important difference between Ethereum and NEAR we need to keep in mind. On Ethereum, when you deploy a contract, you are executing EVM bytecode where the output is the "runtime" EVM bytecode that contains the contract logic. Whereas on NEAR, deployment is simply storing the wasm bytecode directly. Therefore, NEAR contracts typically use a pattern where they have an `init` function which is called once before the contract can be used normally. Mapping a Solidity constructor compiled to EVM bytecode into an `init` function is non-trivial because the logic for the constructor would be in the deployment EVM bytecode, while the main contract logic would be in the runtime EVM bytecode. I think perhaps the right way to do this is to have the `evm2near` compiler analyze the deployment bytecode first, and determine the runtime bytecode from this analysis. I think this is a non-trivial amount of work, but certainly worthwhile in the long run. In the meantime, maybe the easiest thing to do for you would be to following the NEAR `init` pattern in your Solidity code directly (i.e. do not have a constructor, but have a normal function that can initialize the contract).

In the case of events, it would be nice to have `evm2near` compile them into a format compatible with NEP-297, which [defines the events structure](https://nomicon.io/Standards/EventsFormat) for the NEAR ecosystem. This is certainly doable, but requires  some work to parse the events out of the contract ABI and then do the mapping into the NEAR format.

Open source contributions are welcome! If you want to tackle any of these issues, feel free to let us know.
